### ISSUE TITLE
Tracking progress toward next release of SwiftDoc.org

### ISSUE THREAD

**Issue by natecook1000** [SwiftDocOrg/swiftdoc.org#19]
## swiftdoc.org
- [ ] De-emphasize bold headers, seriously, I mean come on
- [ ] Remove accordion menus
- [ ] Add intra-page navigation to sections
- [ ] Indicate unimplemented elements for protocols
- [ ] Add indicator for non-Swift standard library items (like `CGRect`) to resolve #8 
- [ ] Add intra-page behavioral tools:
    - [ ] Show/hide all
    - [ ] Show inherited declarations (in protocols)
    - [ ] Show required elements (in protocols)

## swiftdoc-parser
- [ ] Figure out type aliases for collections when not declared
- [ ] Remove unnecessary lines from inheritance graphs
- [ ] Move default implementations into type declaration when they always apply, like `Array.map()`
- [ ] Remove default implementations that can never apply, like `where SubSequence == Self` for `Array`
- [ ] For integrated default implementations, replace protocol-scoped parameter & return types with type-scoped versions
- [ ] Note whether methods/vars are implemented via default protocol implementations—requires checking for requirements and imps in inherited protocols
- [ ] Show inherited protocols that require an item
- [ ] Generate individual JSON files for each element in the destination directory
